services:
  - type: web
    name: detective-bot
    runtime: python
    repo: https://github.com/xok1mov67/detective_bot
    plan: free
    region: singapore
    buildCommand: pip install python-telegram-bot==20.7
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 7638494951:AAHIB_5bVJp0MqCw9FmX2yZ1kLmN3oPqR
